DROP TABLE IF EXISTS PETS, USERS;

CREATE TABLE PETS(
     ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
     BREED VARCHAR(256)
);


CREATE TABLE USERS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(256),
    AGE INT,
    PET_ID BIGINT REFERENCES PETS(ID)
);
